apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment
  namespace: frontend
spec:
  replicas: 10  
  selector:
    matchLabels:
      app: stress-app
  template:
    metadata:
      labels:
        app: stress-app
    spec:
      containers:
      - name: stress-container
        image: nginx
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 80
